config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :accounts
  get 'homes/view'

  resources :products
  root to: "homes#view"
  get 'accounts/index'

end

app/models/account.rb
class Account
  include Mongoid::Document
  field :username, type: String
  field :password, type: String
end

app/models/product.rb
class Product
  include Mongoid::Document
  field :MaSP, type: String
  field :TenSP, type: String
  field :GiaBan, type: String
  field :NgaySanXuat, type: Date
  field :SoLuongBan, type: String
  field :DoanhThu, type: String
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:username, :password)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!, :except => [:index]
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def view
    @products = Product.all
  end
  def products_by_day
   render json: Product.group_by_day(:created_at).count
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end
  def view
    @products = Product.all
  end
  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:MaSP, :TenSP, :GiaBan, :NgaySanXuat, :SoLuongBan, :DoanhThu)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.username %></td>
        <td><%= account.password %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @account.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @account.password %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/homes/view.html.erb
<div class="clear"></div>
<div class="row">
	<div class="col-md-6">
		<label>Thong ke tu ngay: </label></br>
		<input type="text" value=""></br>
		<label>Den ngay: </label></br>
		<input type="text" value=""></br>
		<button type="button" class="btn btn-success">Thong ke</button>
	<%= link_to 'Quan ly Products', products_path,:class => "btn btn-primary" %>
	</div>
</div>
<div class="row">
  <!-- Line Chart - Single Series -->
  <div class="col-xs-12 col-md-12">
    <h3>Thong ke Doanh Thu Ban San Pham</h3>
    <% @products.each do |t| %>
    <%= column_chart [
	  {name: "Doanh Thu", data: t.DoanhThu }
	] %>
	<% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ThongKe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
<script src="http://code.highcharts.com/highcharts.js"></script>
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
</head>
<body>
<div class="container">
	<div>
	<% if user_signed_in? %>
	    Welcome <%=  current_user.email %>
	    <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
	<% else %>
	    <%= link_to "Sign in", new_user_session_path%> or <%= link_to "Sign up", new_user_registration_path %>
	<% end %>
	</div>
	<%= yield %>
</div>
</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<table>
  <tr>
    <td><%= f.label :MaSP %></td>
    <td><%= f.text_field :MaSP %></td>
  </tr>
  <tr>
    <td><%= f.label :TenSP %></td>
    <td><%= f.text_field :TenSP %></td>
  </tr>
  <tr>
    <td><%= f.label :GiaBan %></td>
    <td><%= f.text_field :GiaBan %></td>
  </tr>
  <tr>
    <td><%= f.label :NgaySanXuat %></td>
    <td><%= f.text_field :NgaySanXuat %></td>
  </tr>
  <tr>
    <td><%= f.label :SoLuongBan %></td>
    <td><%= f.text_field :SoLuongBan %></td>
  </tr>
  <tr>
    <td><%= f.label :DoanhThu %></td>
    <td><%= f.text_field :DoanhThu %></td>
  </tr>
</table>
<div class="actions">
  <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table class="table">
  <thead>
    <tr>
      <th>Mã SP</th>
      <th>Tên Sp</th>
      <th>Giá ban</th>
      <th>Ngày san xuat</th>
      <th>So luong ban</th>
      <th>Doanh thu</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.MaSP %></td>
        <td><%= product.TenSP %></td>
        <td><%= product.GiaBan %></td>
        <td><%= product.NgaySanXuat %></td>
        <td><%= product.SoLuongBan %></td>
        <td><%= product.DoanhThu %></td>
        <td><%= link_to 'View', product,:class => "btn btn-info" %> 
            <%= link_to 'Edit', edit_product_path(product), :class => "btn btn btn-warning" %> 
            <%= link_to 'Destroy', product,:class => "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path,:class => "btn btn-primary" %>
<a href="../" class="btn btn-success">Xem report</a>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Masp:</strong>
  <%= @product.MaSP %>
</p>

<p>
  <strong>Tensp:</strong>
  <%= @product.TenSP %>
</p>

<p>
  <strong>Giaban:</strong>
  <%= @product.GiaBan %>
</p>

<p>
  <strong>Ngaysanxuat:</strong>
  <%= @product.NgaySanXuat %>
</p>

<p>
  <strong>Soluongban:</strong>
  <%= @product.SoLuongBan %>
</p>

<p>
  <strong>Doanhthu:</strong>
  <%= @product.DoanhThu %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>